#!/usr/bin/env perl
# =========================================================================== #
# (c) Jojess Fournier 20240706                                                #
# --------------------------------------------------------------------------- #
#                                                                             #
# there's proly no reason for anybody else to use this haha                   #
#                                                                             #
# --------------------------------------------------------------------------- #
# Copyright (C) 2023 Jojess Fournier                                          #
#                                                                             #
# This program is free software: you can redistribute it and/or modify it     #
# under the terms of the GNU General Public License as published by the Free  #
# Software Foundation, either version 3 of the License, or (at your option)   #
# any later version.                                                          #
#                                                                             #
# This program is distributed in the hope that it will be useful, but         #
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY  #
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License     #
# for more details.                                                           #
#                                                                             #
# You should have received a copy of the GNU General Public License along     #
# with this program. If not, see https://www.gnu.org/licenses/.               #
#                                                                             #
# LICENSE described in project "/LICENSE" file.                               #
#                                                                             #
# --------------------------------------------------------------------------- #
#                                                                             #
# morbo kumosys2024 daemon -m production -l http://*:8095
#                                                                             #
# =========================================================================== #

use JSON;
use WWW::Mechanize;
use Mojolicious::Lite -signatures;

use lib 'lib';
use Kumo::Sys2024;
use POSIX qw(strftime);

my $kumosys = Kumo::Sys2024->new();


get '/' => sub ($c) {
   $c->render(text => 'OwO UwU OwO');
   $c->redirect_to('/heartbeat');
};

get '/heartbeat' => sub($c) {   
   $c->render(text=>1);
};

get '/jikans' => sub($c) {
  my $time = strftime "%H:%M:%S", localtime;
  $c->render(text=>"".$time);
};

get '/jikan' => sub($c) {
  $c->render(text=>"".localtime);
};

get '/tenki' => sub($c) {
  $c->render(text=>"wip tho");
};

get '/test' => sub($c) {
  $c->render(text=>"hewwo");
};

get '/update' => sub($c) {
   $kumosys->log("msg", "update triggered... :3");
   $kumosys->update();
};

# 
# get '/tenki' => sub($c) {
#   $c->render(text=>""."testing");
# };

app->start;


# exit;



#app->start('daemon', '-l', 'http://*:3055');


__DATA__
@@ jojessf.html
<html>
<head>
<title>Jojess Fournier</title>
<meta charset="UTF-8">
<!-- I am not a front end developer.  Nor do I want to be.  -Jojess -->
<style>
      a img {
        border: 10;
      }
      body {
        background-color: #311432;
        font-family: "Lucida Console", Lucida, monospace 
      }
      #notfound {
        background: url(/mojo/notfound2.png);
        height: 62px;
        left: 50%;
        margin-left: -153px;
        margin-top: -31px;
        position:absolute;
        top: 50%;
        width: 306px;
      }
      #linkbar {
        left: 0%;
        position: fixed;
        top: 55%;         
      }
      #noraptor {
         display: block;
      }

      #logoZ {
        left: 50%;
        top: 5%;
        margin-left: -153px;
        margin-top: -31px;
        position:absolute;
        height: 100%;
        width: 100%;
      }
      
      #cpago {
        margin: auto;
       margin-top: 16px;
       margin-left: 32px;
        height: 100%;
        width: 100%; 
      }
      
         #cpagobg {
            background-image: url("artsycodeblob.png");
            background-repeat: repeat;
         }
      
         #logo {
           margin: auto;
           position:absolute;
           height: 100%;
           width: 100%;
         }
         #butt {
            color: #ffffff;
            height: 128px;
            width: 128px;
         }
         #textuwu {
            color: #ffffff;
            display: block;
            position:absolute;
         }
         
         #termmain {
            display: text;
            margin-left: 2%;
            height: 640px;
            width: 480px;
            border: solid;
            border-with: 1px;
            border-color: #777777;
            background-color: #101010;
            color: #EEEEEE;
            overflow: auto;
            max-height: 30%;
            font-size: 24;
         }
         #termtext {
            width: 33%;
            border: solid;
            border-with: 1px;
            border-color: #777777;
            background-color: #101010;
            color: #999999;
         }
    </style>
</head>
  <body id="cpagobg">
    
<!-- input type="text" id="termtext" -->
       <div id="logo"><img src="transjojess.net.png"></div><br><br><br><br><br><br><br><br><br><br>
       
         <div id="termmain"></div>
       
         
         <div id="linkbar">
            <a href="https://www.linkedin.com/in/jess-fournier-0b831672/"><img alt="LinkedIn" id="butt" src="/linkedin.ico"></a>
            <a href="https://metacpan.org/search?size=20&q=jojess+fournier"><img alt="CPAN" id="butt" src="/metacpan.ico"></a>
            <a href="https://github.com/jojessf">
                  <svg height="128" aria-hidden="true" viewBox="0 0 16 16" version="1.1" width="128" data-view-component="true" class="octicon octicon-mark-github v-align-middle color-fg-default">
                     <path d="M8 0c4.42 0 8 3.58 8 8a8.013 8.013 0 0 1-5.45 7.59c-.4.08-.55-.17-.55-.38 0-.27.01-1.13.01-2.2 0-.75-.25-1.23-.54-1.48 1.78-.2 3.65-.88 3.65-3.95 0-.88-.31-1.59-.82-2.15.08-.2.36-1.02-.08-2.12 0 0-.67-.22-2.2.82-.64-.18-1.32-.27-2-.27-.68 0-1.36.09-2 .27-1.53-1.03-2.2-.82-2.2-.82-.44 1.1-.16 1.92-.08 2.12-.51.56-.82 1.28-.82 2.15 0 3.06 1.86 3.75 3.64 3.95-.23.2-.44.55-.51 1.07-.46.21-1.61.55-2.33-.66-.15-.24-.6-.83-1.23-.82-.67.01-.27.38.01.53.34.19.73.9.82 1.13.16.45.68 1.31 2.69.94 0 .67.01 1.3.01 1.49 0 .21-.15.45-.55.38A7.995 7.995 0 0 1 0 8c0-4.42 3.58-8 8-8Z"></path>
                  </svg>
            </a>
            <a href="https://nyxa.jojess.net/@jojess"><img alt="Mastodon" id="butt" src="/masto.ico"></a>
            <a href="https://unilinkgroup.com"><img alt="Current Gig" id="butt" src="/termu3.ico"></a>

            <a href="http://kumosys2024.jojess.net"><img alt="Awoo!" id="noraptor" src="/mojo/noraptor.png"></a>

         </div><!--linkbar-->
      
        <script type="text/javascript">
         const maxlen = 512;
         const div = document.getElementById("termmain");
         
         console.log("┬─┬ ノ( ゜-゜ノ)");
         div.innerHTML = div.innerHTML+"<br>"+"  Jojess Fournier";
         div.innerHTML = div.innerHTML+"<br>"+" ";
         div.innerHTML = div.innerHTML+"<br>"+"  Project Manager";
         div.innerHTML = div.innerHTML+"<br>"+"  Perl Developer";
         div.innerHTML = div.innerHTML+"<br>"+"  Linux Sysadmin";
         div.innerHTML = div.innerHTML+"<br>"+"  EDI & ERP Integrator";
         div.innerHTML = div.innerHTML+"<br>"+" ";
         div.innerHTML = div.innerHTML+"<br>"+"  jess@unilinkgroup.com";
         div.innerHTML = div.innerHTML+"<br>"+"  jojessfournier@gmail.com";
         div.innerHTML = div.innerHTML+"<br>"+" ";
         console.log("(╯°□°）╯︵ ┻━┻");
         
         const KEYIN = "";         
         
         console.log(" ... ");
         console.log("  ");
         console.log(" ùωú ");
        
         </script>
  </body><!--cpagobg-->
</html>



@@ console.html
<html>
<head>
<meta charset="UTF-8">
<!-- I am not a front end developer.  Nor do I want to be.  x3 -->
<style>
#termmain {
 width: 100%;
 height: 640px;
 border: solid;
 border-with: 1px;
 border-color: #777777;
 color: #777777;
}
#termtext {
 width: 100%;
 border: solid;
 border-with: 1px;
 border-color: #777777;
 background-color: transparent;
 color: #999999;
}
</style>
</head>
<body bgcolor=black>
<div id="termmain"></div>
<input type="text" id="termtext">

<script type="text/javascript">
   const maxlen = 512;
   const prompt = document.getElementById("termtext");
   const div = document.getElementById("termmain");
   prompt.addEventListener("keypress", keypress);
   function keypress(e) {
      if(e.keyCode==13&&prompt.value!="") {
         if(prompt.value.length > maxlen) {
            prompt.value = prompt.value.substr(0, maxlen);
            console.log("truncated to "+prompt.value);
         }
         div.innerHTML = div.innerHTML+"<br>"+prompt.value;
         if(prompt.value="uwu"){
            div.innerHTML+"<br>"+"owo";
         }            
         if(prompt.value="owo"){
            div.innerHTML+"<br>"+"uwu";
         }
         console.log("prompt: "+prompt.value);
         prompt.value = "";
      }
   }

</script>
</body>
</html>


@@ scroll.html
<head>
<style>
div.scroll
{
background-color:#00FFFF;
width:40%;
height:200PX;
FLOAT: left;
margin-left: 5%;
padding: 1%;
overflow:scroll;
}


</style>
</head>

<body>



<div class="scroll">You can use the overflow property when you want to have better       control of the layout. The default value is visible.better control of the layout. The default value is visible.better control of the layout. The default value is visible.better control of the layout. The default value is visible.better control of the layout. The default value is visible.better control of the layout. The default value is visible.betterYou can use the overflow property when you want to have better       control of the layout. The default value is visible.better control of the layout. The default value is visible.better control of the layout. The default value is visible.better control of the layout. The default value is visible.better control of the layout. The default value is visible.better control of the layout. The default value is visible.better </div>


</body>
</html>